version: '3.1'

services:
  RecLetterBackend:
    image: ssuyas/recletter_backend
    container_name: RecLetterBackend
    restart: unless-stopped
    ports:
      - "8081:8081"
    networks:
      - RecLetterNetwork
    volumes:
      - ./private_cloudfront_key.pem:/private_cloudfront_key.pem
    environment:
      DB_URL: ${DB_URL}
      USER_NAME: ${USER_NAME}
      USER_PASSWORD: ${USER_PASSWORD}
      MAIL_ID: ${MAIL_ID}
      MAIL_SECRET: ${MAIL_SECRET}
      AWS_ACCESS: ${AWS_ACCESS}
      AWS_SECRET: ${AWS_SECRET}
      AWS_REGION: ${AWS_REGION}
      AWS_BUCKET: ${AWS_BUCKET}
      AWS_FRONT: ${AWS_FRONT}
      AWS_CLOUDFRONT_DOMAIN: ${AWS_CLOUDFRONT_DOMAIN}
      AWS_CLOUDFRONT_KEY: ${AWS_CLOUDFRONT_KEY}
      AWS_CLOUDFRONT_KEY_ID: ${AWS_CLOUDFRONT_KEY_ID}
      JWT_KEY: ${JWT_KEY}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      OPENVIDU_URL: ${OPENVIDU_URL}
      OPENVIDU_SECRET: ${OPENVIDU_SECRET}
    env_file:
      - .env

  video1:
    image: ssuyas/recletter_video
    container_name: RecLetterVideo_1
    restart: unless-stopped
    networks:
      - RecLetterNetwork
    ports:
      - ${RECLETTER_VIDEO_PORT_1}:${RECLETTER_VIDEO_PORT_1}
    environment:
      PORT_NUMBER: ${RECLETTER_VIDEO_PORT_1}
      AWS_ACCESS: ${AWS_ACCESS}
      AWS_SECRET: ${AWS_SECRET}
      AWS_REGION: ${AWS_REGION}
      AWS_BUCKET: ${AWS_BUCKET}
      PYTHONPATH: /
      KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS}
      KAFKA_LETTER_REQUEST_TOPIC: ${KAFKA_LETTER_REQUEST_TOPIC}
      KAFKA_ASSET_DOWNLOADINFO_TOPIC: ${KAFKA_ASSET_DOWNLOADINFO_TOPIC}
      KAFKA_LETTER_ENCODINGINFO_TOPIC: ${KAFKA_LETTER_ENCODINGINFO_TOPIC}
      KAFKA_LETTER_RESULTINFO_TOPIC: ${KAFKA_LETTER_RESULTINFO_TOPIC}
      KAFKA_LETTER_REQUEST_CONSUMER_GROUP_ID: ${KAFKA_LETTER_REQUEST_CONSUMER_GROUP_ID}
      KAFKA_ASSET_DOWNLOADINFO_CONSUMER_GROUP_ID: ${KAFKA_ASSET_DOWNLOADINFO_CONSUMER_GROUP_ID}
      KAFKA_LETTER_ENCODINGINFO_CONSUMER_GROUP_ID: ${KAFKA_LETTER_ENCODINGINFO_CONSUMER_GROUP_ID}
      KAFKA_LETTER_RESULTINFO_CONSUMER_GROUP_ID: ${KAFKA_LETTER_RESULTINFO_CONSUMER_GROUP_ID}
      KAFKA_LETTER_RESULTINFO_DELETE_CONSUMER_GROUP_ID: ${KAFKA_LETTER_RESULTINFO_DELETE_CONSUMER_GROUP_ID}
    volumes:
      - video-data:/videobackend/${DOWNLOAD_PATH:-download}

  video2:
    image: ssuyas/recletter_video
    container_name: RecLetterVideo_2
    restart: unless-stopped
    networks:
      - RecLetterNetwork
    ports:
      - ${RECLETTER_VIDEO_PORT_2}:${RECLETTER_VIDEO_PORT_2}
    environment:
      PORT_NUMBER: ${RECLETTER_VIDEO_PORT_2}
      AWS_ACCESS: ${AWS_ACCESS}
      AWS_SECRET: ${AWS_SECRET}
      AWS_REGION: ${AWS_REGION}
      AWS_BUCKET: ${AWS_BUCKET}
      PYTHONPATH: /
      KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS}
      KAFKA_LETTER_REQUEST_TOPIC: ${KAFKA_LETTER_REQUEST_TOPIC}
      KAFKA_ASSET_DOWNLOADINFO_TOPIC: ${KAFKA_ASSET_DOWNLOADINFO_TOPIC}
      KAFKA_LETTER_ENCODINGINFO_TOPIC: ${KAFKA_LETTER_ENCODINGINFO_TOPIC}
      KAFKA_LETTER_RESULTINFO_TOPIC: ${KAFKA_LETTER_RESULTINFO_TOPIC}
      KAFKA_LETTER_REQUEST_CONSUMER_GROUP_ID: ${KAFKA_LETTER_REQUEST_CONSUMER_GROUP_ID}
      KAFKA_ASSET_DOWNLOADINFO_CONSUMER_GROUP_ID: ${KAFKA_ASSET_DOWNLOADINFO_CONSUMER_GROUP_ID}
      KAFKA_LETTER_ENCODINGINFO_CONSUMER_GROUP_ID: ${KAFKA_LETTER_ENCODINGINFO_CONSUMER_GROUP_ID}
      KAFKA_LETTER_RESULTINFO_CONSUMER_GROUP_ID: ${KAFKA_LETTER_RESULTINFO_CONSUMER_GROUP_ID}
      KAFKA_LETTER_RESULTINFO_DELETE_CONSUMER_GROUP_ID: ${KAFKA_LETTER_RESULTINFO_DELETE_CONSUMER_GROUP_ID}
    volumes:
      - video-data:/videobackend/${DOWNLOAD_PATH:-download}

  video3:
    image: ssuyas/recletter_video
    container_name: RecLetterVideo_3
    restart: unless-stopped
    networks:
      - RecLetterNetwork
    ports:
      - ${RECLETTER_VIDEO_PORT_3}:${RECLETTER_VIDEO_PORT_3}
    environment:
      PORT_NUMBER: ${RECLETTER_VIDEO_PORT_3}
      AWS_ACCESS: ${AWS_ACCESS}
      AWS_SECRET: ${AWS_SECRET}
      AWS_REGION: ${AWS_REGION}
      AWS_BUCKET: ${AWS_BUCKET}
      PYTHONPATH: /
      KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS}
      KAFKA_LETTER_REQUEST_TOPIC: ${KAFKA_LETTER_REQUEST_TOPIC}
      KAFKA_ASSET_DOWNLOADINFO_TOPIC: ${KAFKA_ASSET_DOWNLOADINFO_TOPIC}
      KAFKA_LETTER_ENCODINGINFO_TOPIC: ${KAFKA_LETTER_ENCODINGINFO_TOPIC}
      KAFKA_LETTER_RESULTINFO_TOPIC: ${KAFKA_LETTER_RESULTINFO_TOPIC}
      KAFKA_LETTER_REQUEST_CONSUMER_GROUP_ID: ${KAFKA_LETTER_REQUEST_CONSUMER_GROUP_ID}
      KAFKA_ASSET_DOWNLOADINFO_CONSUMER_GROUP_ID: ${KAFKA_ASSET_DOWNLOADINFO_CONSUMER_GROUP_ID}
      KAFKA_LETTER_ENCODINGINFO_CONSUMER_GROUP_ID: ${KAFKA_LETTER_ENCODINGINFO_CONSUMER_GROUP_ID}
      KAFKA_LETTER_RESULTINFO_CONSUMER_GROUP_ID: ${KAFKA_LETTER_RESULTINFO_CONSUMER_GROUP_ID}
      KAFKA_LETTER_RESULTINFO_DELETE_CONSUMER_GROUP_ID: ${KAFKA_LETTER_RESULTINFO_DELETE_CONSUMER_GROUP_ID}
    volumes:
      - video-data:/videobackend/${DOWNLOAD_PATH:-download}

  app:
    image: ssuyas/recletter_frontend
    container_name: RecLetterFrontend
    restart: unless-stopped
    network_mode: host
    depends_on:
      - RecLetterBackend
    volumes:
      - ./.env:/usr/share/nginx/html/.env

networks:
  RecLetterNetwork:
    external: true

volumes:
  video-data:
