version: '3'

services:
  redis:
    image: redis:7.2.3
    container_name: RecLetterRedis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - recletter-network

  mariadb:
    image: mariadb:10.4
    container_name: RecLetterMariaDB
    ports:
      - "3306:3306"
    volumes:
      - mariadb-data:/lib/var/mysql
      - ../backend/db/initdb.d:/docker-entrypoint-initdb.d
    environment:
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${USER_NAME}
      MARIADB_PASSWORD: ${USER_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      TZ: Asia/Seoul
    networks:
      - recletter-network
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

  zookeeper:
    image: bitnami/zookeeper:3.8.3
    container_name: RecLetterZookeeper
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - zookeeper-data:/bitnami/zookeeper
    networks:
      - recletter-network

  kafka:
    image: bitnami/kafka:3.6
    container_name: RecLetterKafka
    ports:
      - "9093:9093"
    expose:
      - "9093"
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CREATE_TOPICS="kafka_capstone_event_bus:1:1"
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:9093
      - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    networks:
      - recletter-network
    volumes:
      - kafka-data:/bitnami/kafka

volumes:
  redis-data:
  mariadb-data:
  kafka-data:
  zookeeper-data:

networks:
  recletter-network:

